services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    platform: "linux/amd64"

volumes:
  pg-data:
